### ISSUE TITLE
node-red crashing: Cannot read property 'name' of undefined at passMsg (/home/pi/node-red-slack/slackpost.js:105:49)

### ISSUE THREAD

**Issue by janvda** [janvda/pi3one#7]
the log
```
22 Jan 17:59:35 - [info] [mqtt-broker:nuc1] Connected to broker: mqtt://nuc1:1883
22 Jan 17:59:35 - [info] [Slack Bot In:pi3one slackbot] in: Logged in:
22 Jan 17:59:36 - [red] Uncaught Exception:
22 Jan 17:59:36 - TypeError: Cannot read property 'name' of undefined
at passMsg (/home/pi/node-red-slack/slackpost.js:105:49)
at Client.<anonymous> (/home/pi/node-red-slack/slackpost.js:97:17)
at emitOne (events.js:116:13)
at Client.emit (events.js:211:7)
at Client.onMessage (/home/pi/node-red-slack/node_modules/slack-client/src/client.js:492:14)
at WebSocket.<anonymous> (/home/pi/node-red-slack/node_modules/slack-client/src/client.js:149:24)
at emitTwo (events.js:126:13)
at WebSocket.emit (events.js:214:7)
at Receiver.ontext (/home/pi/node-red-slack/node_modules/ws/lib/WebSocket.js:816:10)
at /home/pi/node-red-slack/node_modules/ws/lib/Receiver.js:477:18
at Receiver.applyExtensions (/home/pi/node-red-slack/node_modules/ws/lib/Receiver.js:364:5)
at /home/pi/node-red-slack/node_modules/ws/lib/Receiver.js:466:14
at Receiver.flush (/home/pi/node-red-slack/node_modules/ws/lib/Receiver.js:340:3)
at Receiver.finish (/home/pi/node-red-slack/node_modules/ws/lib/Receiver.js:482:12)
at Receiver.expectHandler (/home/pi/node-red-slack/node_modules/ws/lib/Receiver.js:457:31)
at Receiver.add (/home/pi/node-red-slack/node_modules/ws/lib/Receiver.js:95:24)
nodered.service: main process exited, code=exited, status=1/FAILURE
Unit nodered.service entered failed state.
nodered.service holdoff time over, scheduling restart.
Stopping Node-RED graphical event wiring tool...
Starting Node-RED graphical event wiring tool...
Started Node-RED graphical event wiring tool.
22 Jan 17:59:38 - [info]
Welcome to Node-RED
===================
22 Jan 17:59:38 - [info] Node-RED version: v0.19.1
22 Jan 17:59:38 - [info] Node.js  version: v8.11.4
22 Jan 17:59:38 - [info] Linux 4.9.35-v7+ arm LE
22 Jan 17:59:40 - [info] Loading palette nodes
22 Jan 17:59:47 - [info] Dashboard version 2.9.6 started at /ui
22 Jan 17:59:48 - [info] Settings file  : /home/pi/.node-red/settings.js
22 Jan 17:59:48 - [info] HTTP Static    : /home/pi/.node-red/projects/pi3one/http_static
22 Jan 17:59:48 - [info] Context store  : 'default' [module=memory]
22 Jan 17:59:48 - [info] User directory : /home/pi/.node-red
22 Jan 17:59:49 - [info] Server now running at http://127.0.0.1:1880/
22 Jan 17:59:49 - [info] Active project : pi3one
22 Jan 17:59:49 - [info] Flows file     : /home/pi/.node-red/projects/pi3one/flows_pi3one.json
22 Jan 17:59:49 - [info] Starting flows
[Sun Jan 22 2023 17:59:50 GMT+0100 (CET)] INFO Connecting...
22 Jan 17:59:50 - [error] [mqtt out:8183e993.979428] missing broker configuration
22 Jan 17:59:50 - [warn] [google-credentials:6e76318c.44294] trying to refresh token due to expiry
22 Jan 17:59:50 - [info] Started flows
22 Jan 17:59:50 - [info] [sqlitedb:d4b7b30a.7abac] opened /mnt/wd1tb_media/media/data/sqlite/nodered_jvda.db ok
22 Jan 17:59:50 - [info] [mqtt-broker:9c9ae2bc.63652] Connected to broker: mqtt://pi3one:1883
22 Jan 17:59:50 - [info] [mqtt-broker:pi3three mqtt broker] Connected to broker: mqtt://pi3three:1883
22 Jan 17:59:50 - [info] [mqtt-broker:nuc1] Connected to broker: mqtt://nuc1:1883
22 Jan 17:59:51 - [info] [Slack Bot In:pi3one slackbot] in: Logged in:
22 Jan 17:59:51 - [red] Uncaught Exception:
22 Jan 17:59:51 - TypeError: Cannot read property 'name' of undefined
at passMsg (/home/pi/node-red-slack/slackpost.js:105:49)
at Client.<anonymous> (/home/pi/node-red-slack/slackpost.js:97:17)
at emitOne (events.js:116:13)
at Client.emit (events.js:211:7)
at Client.onMessage (/home/pi/node-red-slack/node_modules/slack-client/src/client.js:492:14)
at WebSocket.<anonymous> (/home/pi/node-red-slack/node_modules/slack-client/src/client.js:149:24)
at emitTwo (events.js:126:13)
at WebSocket.emit (events.js:214:7)
at Receiver.ontext (/home/pi/node-red-slack/node_modules/ws/lib/WebSocket.js:816:10)
at /home/pi/node-red-slack/node_modules/ws/lib/Receiver.js:477:18
at Receiver.applyExtensions (/home/pi/node-red-slack/node_modules/ws/lib/Receiver.js:364:5)
at /home/pi/node-red-slack/node_modules/ws/lib/Receiver.js:466:14
at Receiver.flush (/home/pi/node-red-slack/node_modules/ws/lib/Receiver.js:340:3)
at Receiver.finish (/home/pi/node-red-slack/node_modules/ws/lib/Receiver.js:482:12)
at Receiver.expectHandler (/home/pi/node-red-slack/node_modules/ws/lib/Receiver.js:457:31)
at Receiver.add (/home/pi/node-red-slack/node_modules/ws/lib/Receiver.js:95:24)
nodered.service: main process exited, code=exited, status=1/FAILURE
Unit nodered.service entered failed state.
nodered.service holdoff time over, scheduling restart.
Stopping Node-RED graphical event wiring tool...
Starting Node-RED graphical event wiring tool...
Started Node-RED graphical event wiring tool.
22 Jan 17:59:54 - [info]
Welcome to Node-RED
===================
22 Jan 17:59:54 - [info] Node-RED version: v0.19.1
22 Jan 17:59:54 - [info] Node.js  version: v8.11.4
22 Jan 17:59:54 - [info] Linux 4.9.35-v7+ arm LE
22 Jan 17:59:55 - [info] Loading palette nodes
```

**Comment by janvda** [comment]
The flows are now executed on nuc2 and to overcome this problem I had to disable all slack in / out nodes.

**Comment by janvda** [comment]
closed as flows are now executed on nuc2 (see nuc2-pi3one).
See also:
* https://github.com/janvda/nuc2-pi3one/issues/3
